language: node_js
node_js:
  - "14.16.0"
env:
  friend=Jane
  _friend=john
  friend_=Travis
jobs:
  include:
    - node_js: "14.16.0"
      script: npm install && cowsay Hello $friend
    - node_js: "14.16.0"
      script: npm install && cowsay Hello $_friend
    - node_js: "14.16.0"
      script: npm install && cowsay Hello $friend_
    - node_js: "14.16.0"
      script: npm install && cowsay Hello Back!!  