language: node_js
node_js:
  - "14.16.0"
env:
  friend=Jane
  _friend=john
  friend_=Travis
script:
  - echo 'Starting build..'
  - echo 'Installing dependencies..'
  - npm install
  - cowsay Hello $friend